image: docker:19.03.1

variables:
    DOCKER_HOST: tcp://localhost:2376

services:
    - docker:dind

stages:
    - build

before_script:
  - docker info

build_api:
  stage: build
  only:
    - master
    - web
  before_script:
   
    - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
  script:
    - docker build -f ./src/Api/Api/Dockerfile -t ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest .
    - docker push ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest
  after_script:
    - docker logout ${AZURE_REGISTRY}

build_entity_observer_service:
    stage: build
    only:
        - master
        - web
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/EntitiesObserver/Dockerfile -t ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest .
        - docker push ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

build_notification_service:
    stage: build
    only:
        - master
        - web
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/NotificationService/Dockerfile -t ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest .
        - docker push ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

#run_tests:
#    stage: run_tests
#    only: master
#    script:
#        - "cd $test"
#        - "dotnet test"

