image: docker:18-git

services:
    - docker:18-dind

stages:
    - test
    - build

before_script:
  - docker info

build_api:
  stage: build
  only:
    - master
    - web
  before_script:
    - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
  script:
    - docker build -f ./src/Api/Api/Dockerfile -t ${AZURE_REGISTRY}/api:latest ./src/Api
    - docker push ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest
  after_script:
    - docker logout ${AZURE_REGISTRY}

build_entity_observer_service:
    stage: build
    only:
        - master
        - web
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/EntitiesObserver/Dockerfile -t ${AZURE_REGISTRY}/entity-observer-service:latest ./src/Api
        - docker push ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

build_notification_service:
    stage: build
    only:
        - master
        - web
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/NotificationService/Dockerfile -t ${AZURE_REGISTRY}/notification-service:latest ./src/Api
        - docker push ${AZURE_REGISTRY}/${AZURE_PROJECT_PATH}:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

test_services:
    stage: test
    before_script:
        - cd src/Api
    script:
        - 'dotnet test Services.Tests\Services.Tests.csproj'
    after_script:
        - cd ../..

test_entities_observer_service:
    stage: test
    before_script:
        - cd src/Api
    script:
        - 'dotnet test EntitiesObserver.Tests\EntitiesObserver.Tests.csproj'
    after_script:
        - cd ../..

test_notification_service:
    stage: test
    before_script:
        - cd src/Api
    script:
        - 'dotnet test NotificationService.Tests\NotificationService.Tests.csproj'
    after_script:
        - cd ../..

        
        
#run_tests:
#    stage: run_tests
#    only: master
#    script:
#        - "cd $test"
#        - "dotnet test"

