
image: mcr.microsoft.com/dotnet/core/sdk:2.2.301

stages:
    - test
    - build

before_script:
  - docker info

build_api:
    stage: build
    only:
        - master
        - web
    image: docker:18-git
    services:
        - docker:18-dind
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/Api/Dockerfile -t ${AZURE_REGISTRY}/api:latest ./src/Api
        - docker push ${AZURE_REGISTRY}/api:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

build_entity_observer_service:
    stage: build
    only:
        - master
        - web
    image: docker:18-git
    services:
        - docker:18-dind
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/EntitiesObserver/Dockerfile -t ${AZURE_REGISTRY}/entity-observer-service:latest ./src/Api
        - docker push ${AZURE_REGISTRY}/entity-observer-service:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

build_notification_service:
    stage: build
    only:
        - master
        - web
    image: docker:18-git
    services:
        - docker:18-dind
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Api/NotificationService/Dockerfile -t ${AZURE_REGISTRY}/notification-service:latest ./src/Api
        - docker push ${AZURE_REGISTRY}/notification-service:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

build_front:
    stage: build
    only:
        - master
        - web
    image: docker:18-git
    services:
        - docker:18-dind
    before_script:
        - docker login dapracticepoliit.azurecr.io -u ${AZURE_REGISTRY_USER} -p ${AZURE_REGISTRY_PASSWORD}
    script:
        - docker build -f ./src/Ui/Dockerfile -t ${AZURE_REGISTRY}/front:latest ./src/Ui
        - docker push ${AZURE_REGISTRY}/front:latest
    after_script:
        - docker logout ${AZURE_REGISTRY}

test_services:
    stage: test
    only:
        - master
        - web
    script:
        - dotnet test src\Api\NotificationService.Tests