apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          env:
            - name: SA_PASSWORD
              value: "Pass@word"
            - name: MSSQL_SA_PASSWORD
              value: "Pass@word"
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - name: mssql
              containerPort: 1433
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-data