apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: notification-service
spec:
    template:
        metadata:
            labels:
                app: notification-service
        spec:
            containers:
              - name: notification-service
                image: dapoliit.azurecr.io/notification-service:latest
                env:
                    - name: RabbitmqConfig__Host
                      value: rabbitmq://rabbitmq
                    - name: RabbitmqConfig__Username
                      value: "usr"
                    - name: RabbitmqConfig__Password
                      valueFrom:
                        secretKeyRef:
                          name: dev-config
                          key: RabbitMqConfig__Password
                    - name: RabbitmqConfig__SSLActive
                      value: "false"
            imagePullSecrets:
                - name: azure-ad-secret