apiVersion: v1
kind: Service
metadata:
    name: identity-server
spec:
    ports:
      - port: 9000
        targetPort: 80
        protocol: TCP
    selector:
        app: identity-server
    type: NodePort