apiVersion: v1
kind: Service
metadata:
    name: identity-server
    labels:
        app: identity-server
spec:
    type: LoadBalancer
    ports:
      - port: 9000
        targetPort: 80 
    selector:
        app: identity-server