kind: Service
apiVersion: v1
metadata:
  name: rabbit-mq
  labels:
    app: rabbit-mq
spec:
  clusterIP: None
  ports:
   - name: http
     protocol: TCP
     port: 15672
   - name: amqp
     protocol: TCP
     port: 5672
  selector:
    app: rabbit-mq