apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: entity-observer-service
spec:
    template:
        metadata:
            labels:
                app: entity-observer-service
        spec:
            containers:
              - name: entities-observer
                image: dapoliit.azurecr.io/entity-observer-service:latest
                env:
                    - name: ConnectionStrings__DefaultConnection
                      value: Server=mssql;Database=master;User=sa;Password=Pass@word;MultipleActiveResultSets=true
                    - name: Redis__ConnectionString
                      value: redis-master:6379,connectRetry=5
                    - name: AppConfig__Host
                      value: rabbitmq://rabbitmq
                    - name: AppConfig__Username
                      value: "usr"
                    - name: AppConfig__Password
                      value: "pass"
                    - name: AppConfig__SSLActive
                      value: "false"
            imagePullSecrets:
                - name: azure-ad-secret